version: '2'
services:
  indexd:
    image: "quay.io/cdis/indexd"
    ports:
      - "8080:80"
  user-api:
    image: "quay.io/cdis/user-api"
    ports:
      - "8081:80"
  gdcapi:
    image: "quay.io/cdis/gdcapi:docker"
    ports:
      - "8082:80"
     
